### ISSUE TITLE
About archives page and tags page didn't support pagination 

### ISSUE THREAD

**Issue by ningyu1** [wd/hugo-fabric#3]
Can authors consider supporting paging?

Thank you very much！

**Comment by wd** [comment]
Yes, I'll try it, but I don't have much time now, pull requests are welcome. :)

**Comment by wd** [comment]
I have spent some time on this issue today, it seems Hugo didn't support multiple paginators, since Hugo is just a static site generator, it need to save every pages on the disk, now it only support one paginator. 
The only way to solve this is display all posts in Hugo template, and then using Javascripts to do the pagination, I think maybe display all at once is better than run Javascripts to hide some of the posts.
